# Generated by Django 6.1.2 on 2026-10-08 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('hex_code', models.CharField(blank=True, max_length=7, verbose_name='Hexadezimalcode')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Zuletzt editiert')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungszeitpunkt')),
            ],
            options={
                'verbose_name': 'Farbe',
                'verbose_name_plural': 'Farben',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('template_type', models.CharField(choices=[('order_confirmation', 'Bestellbestätigung'), ('invoice', 'Rechnung')], default=('order_confirmation', 'Bestellbestätigung'), max_length=20, verbose_name='Vorlagentyp')),
                ('subject', models.CharField(max_length=255, verbose_name='Betreff')),
                ('txt_content', models.TextField(verbose_name='Textinhalt')),
                ('html_content', models.TextField(verbose_name='HTML-Inhalt')),
                ('active', models.BooleanField(default=False, verbose_name='Aktives Template?')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Zuletzt editiert')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungszeitpunkt')),
            ],
            options={
                'verbose_name': 'E-Mail Template',
                'verbose_name_plural': 'E-Mail Templates',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Vollständiger Name')),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.TextField(blank=True, verbose_name='Anmerkung')),
                ('status', models.CharField(choices=[('ordered', 'Bestellung eingegangen'), ('ready_for_pickup', 'Bereit zur Abholung'), ('ready_for_shipment', 'Bereit zum Versand'), ('cancelled', 'Storniert'), ('completed', 'Abgeschlossen')], default=('ordered', 'Bestellung eingegangen'), max_length=20, verbose_name='Bestellstatus')),
                ('is_order_payed', models.BooleanField(choices=[(True, 'Bezahlt'), (False, 'Zahlung ausstehend')], default=False, verbose_name='Bestellung bezahlt?')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Zuletzt editiert')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungszeitpunkt')),
            ],
            options={
                'verbose_name': 'Bestellung',
                'verbose_name_plural': 'Bestellungen',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preis')),
                ('image', models.ImageField(upload_to='shop/products', verbose_name='Bild')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Zuletzt editiert')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungszeitpunkt')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkte',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Zuletzt editiert')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungszeitpunkt')),
            ],
            options={
                'verbose_name': 'Größe',
                'verbose_name_plural': 'Größen',
            },
        ),
        migrations.CreateModel(
            name='CustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('option_type', models.CharField(choices=[('text', 'Text'), ('number', 'Zahl'), ('checkbox', 'Ja/Nein')], max_length=20, verbose_name='Optionstyp')),
                ('required', models.BooleanField(default=False, verbose_name='Pflichtfeld?')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preis')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Zuletzt editiert')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungszeitpunkt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='merchandiseshop.product')),
            ],
            options={
                'verbose_name': 'Personalisierungsoption',
                'verbose_name_plural': 'Personalisierungsoptionen',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Zuletzt editiert')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungszeitpunkt')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colors', to='merchandiseshop.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='merchandiseshop.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sizes', to='merchandiseshop.size')),
            ],
            options={
                'verbose_name': 'Produktvariante',
                'verbose_name_plural': 'Produktvarianten',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Menge')),
                ('customization_details', models.JSONField(blank=True, default=dict, verbose_name='Personalisierungsdetails')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Gesamtpreis')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Zuletzt editiert')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungszeitpunkt')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='merchandiseshop.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='merchandiseshop.productvariant')),
            ],
            options={
                'verbose_name': 'Bestellposition',
                'verbose_name_plural': 'Bestellpositionen',
            },
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'size', 'color'), name='unique_product_variant'),
        ),
    ]
